version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:20.11
    steps:
      # - checkout
      - run: echo "Linting code..."
      - run: echo "npm run lint"
      - run: npm --version

  test:
    docker:
      - image: cimg/node:20.11
    steps:
      # - checkout
      - run: echo "Running tests..."
      - run: echo "npm test"
      - run: npm --version

  package:
    docker:
      - image: cimg/node:20.11
    steps:
      # - checkout
      - run: echo "Building package..."
      - run: echo "npm run build"
      - run: npm --version

  nightly-cleanup:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "cleanup"

workflows:
  build-and-test:
    jobs:
      - lint
      - test
      - package
